spring:
  main:
    web-application-type: servlet
  application:
    name: ingestion-engine
  datasource:
    url: jdbc:postgresql://postgres:5432/decode
    username: ${SPRING_DATASOURCE_USERNAME:decode_user}
    password: ${SPRING_DATASOURCE_PASSWORD:decode_password} 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

minio:
  endpoint: http://minio:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: decode-source-code
