spring:
  main:
    web-application-type: servlet
  application:
    name: ingestion-engine
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 10MB
  datasource:
    url: jdbc:postgresql://postgres:5432/decode
    username: ${SPRING_DATASOURCE_USERNAME:decode_user}
    password: ${SPRING_DATASOURCE_PASSWORD:decode_password} 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  # Increase timeout for large file uploads
  connection-timeout: 300000 # 5 minutes

minio:
  endpoint: http://minio:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: decode-source-code
